### ISSUE TITLE
Estructura de la aplicación (Apartado 04 documentación)

### ISSUE THREAD

**Issue by Pelayo-Rodriguez-Garcia** [Arquisoft/viade_es4a#3]
Acabo de finalizar el apartado 04 de la documentación (solution strategy) En él digo que "seguramente" sigamos la estructura de archivos que sigue la gente de SOLID en el  [ejemplo](https://solid.inrupt.com/docs/writing-solid-apps-with-react) que publican en su web. Os recomiendo que leais esa página y echeis un vistazo a los paquetes src/containers y src/services. Creo que esa es una buena estructura que podemos seguir para el desarrollo.

**Comment by RaulGarciaArenas** [comment]
Yo estoy de acuerdo, lo he estado revisando y me parece bien que lo usemos ya que es la estructura que ellos usan
