### ISSUE TITLE
Apartado 09 (Decisiones de diseño)

### ISSUE THREAD

**Issue by Pelayo-Rodriguez-Garcia** [Arquisoft/viade_es4a#4]
He publicado el primer borrador de este apartado en su rama. En él digo que se usarán las librerías LDFlex y rdflib para leer/escribir en PODS y para tratar con Linked Data respectivamente. Si no estais de acuerdo o encontrais alguna alternativa mejor comentadlo aquí y cambio este apartado. Aún así, estas dos librerías van muy bien con SOLID y ellos las usan en todos los ejemplos.

**Comment by UO264695** [comment]
Yo estoy de acuerdo en utilizar esas librerías
